name: index
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/workflows/requirements.txt
      - name: Index Files with Python Script
        run: |
          python ./.github/workflows/makeIndex.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Indexed Directories
          file_pattern: index.html files/index.html files/*/index.html
